# -*- coding: utf-8 -*-
"""MNIST_Digit_Classification_Using_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xdl08bYTtcf05RvJ6jipa5OsbNHOhsbh
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,datasets,models,Input
from tensorflow.keras.layers import LSTM,Dense

mnist = keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()

input_shape=(28,28)
inputs = Input(shape=input_shape)
rnn_layer = LSTM(128)(inputs)
outputs = Dense(10, activation='softmax')(rnn_layer)
model = models.Model(outputs=outputs,inputs=inputs)

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train,y_train,validation_split=0.1,epochs=10)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['training data','validation'],loc= 'lower right')

